### ISSUE TITLE
Bug in plotPD(): (Error in 'purrr::map2()':),

### ISSUE THREAD

**Issue by GlynR-T** [davidcarslaw/deweather#17]
We carried out some 'deweather' runs last year (June/July 2023) without any problems. However, we have recently attempted to rerun some tests, using the same (identical) input data files, but with the current version of 'deweather', and have encountered a problem with plotPD(). The input file contains 4 years of data at hourly resolution i.e. 35065 rows, including header.
Basically, with the older version of 'deweather' which used the function plotAllPD(), we were able to create a 4 row by 3 column PD plot without any problems (i.e. 11 explanatory variables, plus 'Trend').
However, if we attempt to do the same with plotPD() in the current version of 'deweather', we encounter an error (Error in 'purrr::map2()':), and it fails to plot. 
We managed to get plotPD(mod_no2, variable = "all") to work if we reduced the number of explanatory variables input to buildMod(). However, there appeared to be an additional (related?) bug where at least one of the PD variables was plotted as a category variable on the 'x' axis, when it was in reality a continuous variable (e.g. vehicle speed).
I have emailed further details to David Carslaw.
Should we assume a limit on the number of explanatory variables input to buildMod()?
![Run_55_error01](https://github.com/davidcarslaw/deweather/assets/163730628/fbd8145f-ddf7-4245-92a8-8863e44b8209)
![Run_55_error02](https://github.com/davidcarslaw/deweather/assets/163730628/d8fa1be8-ac13-4853-bf44-bd68f7def867)
![Run_55_error03](https://github.com/davidcarslaw/deweather/assets/163730628/0ec6d045-f2bd-4dfb-bf49-c86762326111)

**Comment by jack-davison** [comment]
Morning Glyn,

I don't believe there should be any upper limit on the number of variables - see dummy example below.

``` r
thedata <- openair::mydata

thedata$TW_Traffic_light <- sample(1:100, size = nrow(thedata), replace = TRUE)
thedata$TW_Traffic_heavy <- sample(1:100, size = nrow(thedata), replace = TRUE)
thedata$TW_mph_LL <- sample(1:100, size = nrow(thedata), replace = TRUE)
thedata$TW_mph_HH <- sample(1:100, size = nrow(thedata), replace = TRUE)
thedata$TW_mph_XX <- sample(1:100, size = nrow(thedata), replace = TRUE)
thedata$TW_mph_YY <- sample(1:100, size = nrow(thedata), replace = TRUE)
thedata$TW_mph_ZZ <- sample(1:100, size = nrow(thedata), replace = TRUE)
thedata$TW_mph_QQ <- sample(1:100, size = nrow(thedata), replace = TRUE)

smalldata <- dplyr::slice_sample(thedata, prop = 0.05)

no2Model <-
  deweather::buildMod(
    smalldata, 
    pollutant = "no2",
    vars = c(
      "trend",
      "ws",
      "wd",
      "week",
      "weekday",
      "hour",
      "TW_Traffic_light",
      "TW_Traffic_heavy",
      "TW_mph_LL",
      "TW_mph_HH",
      "TW_mph_XX",
      "TW_mph_YY",
      "TW_mph_ZZ",
      "TW_mph_QQ"
    )
  )

deweather::plotPD(no2Model)
```

![](https://i.imgur.com/7jpLcY3.png)

<sup>Created on 2024-03-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


More than happy to give this a look if you can provide a reproducible example. Feel free to attach a sample of data here, or if it is too sensitive for GitHub I'd pop it in an email. 

If it's too sensitive to share more widely, I'd also happily take some dummy data or just a data dictionary to tell me the data types of each of your columns.

If there's a worry that `{deweather}` is understanding vehicle speed to be a categorical rather than continuous variable, one thing I'd do is double check that R understands your vehicle speed column to be numeric. You can do this with the `class()` function:

``` r
class(openairmaps::polar_data$nox)
#> [1] "numeric"
class(openairmaps::polar_data$site)
#> [1] "character"
```

<sup>Created on 2024-03-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thanks,
Jack

**Comment by GlynR-T** [comment]
Thanks Jack.
I've just generated an example data file and script (and reproduced the error). I'm not sure how I have managed to break your code. The variable classes look OK.
Please email me at:
admin@glynrhys-tyler.com
and I will email you the files, so hopefully you will be able to reproduce the error. Glyn

**Comment by jack-davison** [comment]
Hi Glyn, 

We've just pushed a fix, so I hope your code should now work with data.frames and tibbles using this new version. 

You've discovered what turned out to be quite an insidious little bug in `{deweather}`, so thanks for bringing it to our attention!

Jack
